server:
  port: 8080
spring:
  cloud:
    gateway:
      default-filters:
        - name: ApiKeyGatewayFilter
          
      routes:
        - id: product-service
          uri: http://localhost:8081/
          predicates:
            - Path=/api/v1/product/**
          filters:
            - name: ApiKeyGatewayFilter

        - id: customer-service
          uri: http://localhost:8082/
          predicates:
            - Path=/api/v1/customer/**